### PR TITLE
[RTM] Fix bug with wrong densities

### LINKED ISSUE #39: Problem with responsive images
<a href="https://github.com/mlwebworker"></img></a> [Issue](https://github.com/contao/core/issues/8807) by @mlwebworker
October 26th, 2017, 19:12 GMT

Es geht um die neue Variante bei Pixeldichte/Skalierungsfaktor - die Breitenbeschreibung (z.B. 300w), die ich sehr begrüße.
Bei einem Test ist mir allerdings zufällig aufgefallen, dass ein für mich nicht nachvollziehbares srcset entsteht, falls die angegebene Breite größer ist als die Breite des Originalbildes.
Beschrieben im Forum https://community.contao.org/de/showthread.php?68549-Responsive-geht-gar-nicht&p=454886&viewfull=1#post454886.
Da wir grundsätzlich nicht ausschließen können, dass Redakteure das auf zu kleine Originalbilder anwenden, sollte dieser Fall m.E. genauso abgefangen werden wie das passiert, wenn ich für ein Bild 600w angebe aber das Originalbild diese Breite gar nicht hergibt.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #39

### CODE REVIEW

File: tests/PictureGeneratorTest.php [hunk 1]
```diff
@@ -240,6 +253,125 @@ function () {
...
+    public function testGenerateWDescriptorSmallImage()
+    {
+        $resizer = $this->createMock(ResizerInterface::class);
+
+        $resizer
+            ->method('resize')
+            ->will($this->returnCallback(
+                function () {
+                    /** @var ResizeConfigurationInterface $config */
+                    $config = func_get_arg(1);
```
Comment (leofeyer) [inline tests/PictureGeneratorTest.php]: O RLY? 😄

Comment (ausi) [reply tests/PictureGeneratorTest.php]: Yeah, It’s a copy paste from the previous method :D

Comment (ausi) [reply tests/PictureGeneratorTest.php]: Done in 83dd8d43100a30b491f46a844de2d3263127564d
